source 'https://rubygems.org'

################## RAILS GEMS

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'


gem 'kaminari'
gem 'simple_form'
gem 'bootstrap-sass'
gem 'smooth_operator'
gem 'cocoon', '1.2.6'
# gem 'smooth_operator', path: '../../smooth_operator'

group :development do
  gem "pry"
  gem 'spring' # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "pry-rails"
  gem 'jazz_hands'
end