source 'https://rubygems.org'

gem "pry"
gem 'slim'
gem 'rake'
gem 'sqlite3'
gem "sinatra-contrib"
gem 'padrino', '0.12.2'
gem 'kaminari', :require => 'kaminari/sinatra'
gem 'activerecord', '>= 3.1', :require => 'active_record'